In [3]:
import numpy as np


In [4]:
student_data=np.random.randint(10,20,(10,5))
print(student_data)

[[13 17 11 12 19]
 [13 16 11 19 11]
 [17 17 11 17 19]
 [13 16 13 19 19]
 [13 11 11 13 15]
 [18 19 12 14 15]
 [11 11 13 11 14]
 [12 18 13 16 15]
 [16 13 19 16 10]
 [13 10 14 18 12]]


In [7]:
stud_avg=student_data.mean(axis=1)
avg=np.mean(student_data,axis=1)
print(avg)
print(stud_avg)

[14.4 14.  16.2 16.  12.6 15.6 12.  14.8 14.8 13.4]
[14.4 14.  16.2 16.  12.6 15.6 12.  14.8 14.8 13.4]
