In [5]:
import numpy as np
data=np.array([23.8,23,56,44,34,23,48])
first_week=data[:8]
fourth_week=data[24:31]
print(first_week)
print(fourth_week)


[23.8 23.  56.  44.  34.  23.  48. ]
[]


In [6]:
data_above_30=data[data>30]
print(data_above_30)

[56. 44. 34. 48.]


In [7]:
import numpy as np

In [13]:
arr_1=np.array([10,20,10,30,11,78,88,100,12,12,38,79])

In [ ]:
print(arr_1.reshape(4,3))

[[ 10  20  10]
 [ 30  11  78]
 [ 88 100  12]
 [ 12  38  79]]


In [14]:
arr_2=arr_1*10
print(arr_2)

[ 100  200  100  300  110  780  880 1000  120  120  380  790]


In [17]:
print(np.vstack((arr_1,arr_2)))

[[  10   20   10   30   11   78   88  100   12   12   38   79]
 [ 100  200  100  300  110  780  880 1000  120  120  380  790]]


In [18]:
arr_1.reshape(3,4).T

array([[ 10,  11,  12],
       [ 20,  78,  12],
       [ 10,  88,  38],
       [ 30, 100,  79]])